col_restaurant_emoji = {
    "Cappuccino (regular) " : "(☕)",
    "Coke/Pepsi (0.33 liter bottle) " : "(🥤)",
    "Domestic Beer (0.5 liter draught) " : "(🍺)",
    "Imported Beer (0.33 liter bottle) " : "(➡🍺)",
    "McMeal at McDonalds (or Equivalent Combo Meal) " : "(🍔)",
    "Meal for 2 People, Mid-range Restaurant, Three-course " : "(👫💵)",
    "Meal, Inexpensive Restaurant " : "(❎💸)",
    "Water (0.33 liter bottle)  " : "(🚰)"
};

col_market_emoji = {'Apples (1kg) ' : "1",
'Banana (1kg) ' : "2",
'Beef Round (1kg) (or Equivalent Back Leg Red Meat) ' : "3",
'Bottle of Wine (Mid-Range) ' : "4",
'Chicken Fillets (1kg) ' : "5",
'Cigarettes 20 Pack (Marlboro) ' : "6",
'Domestic Beer (0.5 liter bottle) ' : "7",
'Eggs (regular) (12) ' : "8",
'Imported Beer (0.33 liter bottle) ' : "9",
'Lettuce (1 head) ' : "10",
'Loaf of Fresh White Bread (500g) ' : "11",
'Local Cheese (1kg) ' : "12",
'Milk (regular), (1 liter) ' : "13",
'Onion (1kg) ' : "14",
'Oranges (1kg) ' : "15",
'Potato (1kg) ' : "16",
'Rice (white), (1kg) ' : "17",
'Tomato (1kg) ' : "18",
'Water (1.5 liter bottle) ' : "19"};